# Generated by Django 5.1.4 on 2024-12-17 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.CharField(choices=[('AM', 'Mañana'), ('PM', 'Tarde')], default='AM', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('edad', models.BigIntegerField()),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.cursos')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.generos')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.horarios')),
            ],
        ),
    ]
